# Generated by Django 3.1.4 on 2021-01-05 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_auto_20210105_1552'),
        ('blog', '0002_auto_20210105_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='autor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='workouts.coach'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
