# Generated by Django 3.1.4 on 2021-01-05 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_slider_subtitle'),
        ('blog', '0004_auto_20210105_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='member',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='workouts.member'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post'),
        ),
    ]
