# Generated by Django 3.1.4 on 2021-01-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date_of_training',
            field=models.DateTimeField(),
        ),
    ]
