# Generated by Django 3.1.4 on 2021-01-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_auto_20210104_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date_of_training',
            field=models.DateField(),
        ),
    ]
