# Generated by Django 3.1.4 on 2021-01-05 14:52

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_auto_20210104_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.AddField(
            model_name='banner',
            name='page',
            field=models.CharField(choices=[('about', 'about'), ('contact', 'contact'), ('blog', 'blog'), ('coach', 'coach'), ('program', 'program')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Body Building', 'Body Building'), ('Aerobic', 'Aerobic'), ('Weight Lifting', 'Weight Lifting'), ('Yoga', 'Yoga'), ('Crossfit', 'Crossfit'), ('Body Fit', 'Body Fit'), ('Gym', 'Gym')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='coach')),
                ('bio', tinymce.models.HTMLField()),
                ('category', models.ManyToManyField(to='workouts.Category')),
            ],
        ),
    ]
