# Generated by Django 3.1.4 on 2021-01-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_auto_20210105_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='subtitle',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
