# Generated by Django 3.1.4 on 2021-01-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0012_auto_20210106_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to='program'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
