# Generated by Django 3.1.4 on 2021-01-06 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0013_auto_20210106_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
