# Generated by Django 3.1.4 on 2021-01-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0014_auto_20210106_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insta_Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='insta_gallery')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
